### ISSUE TITLE
IPv6 Not Working?

### ISSUE THREAD

**Issue by phpHavok** [iptube/SPUDlib#49]
I'm having issues when using IPv6 addresses. The default test applications don't seem to work with them (spudecho/spudtest). I tried IPv6 addresses on my own application as well, and I've tracked down the problem to when `sendmsg` is called from `tube_manager_sendmsg`. It returns error code 19 (`ENODEV`) with message "No such device." I assume it is having problems with the socket that's passed in. The man page for `sendmsg` doesn't even list `ENODEV` as one of its possible errors... I thought maybe it was because my GENI nodes are IPv6 only. So I enabled `IPV6_V6ONLY`. Same problem. Any thoughts?

**Comment by phpHavok** [comment]
I should have been more specific before. This error occurs in whatever application is acting as the server. I can verify that the client sends a connect request over IPv6. When it arrives at the server, inside `tube_manager_wait`, this line fails:

```
if (!tube_send(d.t, SPUD_ACK, false, false, NULL, 0, 0, err)) {
```

Digging in deeper to that function, you can ultimately trace the error to `sendmsg`.

**Comment by hildjj** [comment]
OK, this is a really big deal.  This almost certainly crept in when I did the timer refactor and split v4/v6 onto different sockets.  Can you see if you can factor this down to a small test, so we can ensure that it doesn't regress later?

**Comment by phpHavok** [comment]
I'm working on isolating it now. It's hard to know exactly where the bug crept in, because there was that whole segfault issue before you added the timers. I'll keep you posted. May have some questions.

**Comment by hildjj** [comment]
That refactor changeset was huge.  Before the refactor, there was a single fd to listen on, that did both v4 and v6.  After the change, there are three: v4, v6, and self-pipe for interrupts.  Likely, the send routine is using the wrong socket, an uninitialized one, or something like that.

**Comment by phpHavok** [comment]
I tried using a custom sendmsg_func for the server. The default is just the Linux `sendmsg`. I replaced it with just `sendto`. I sent an invalid payload, but I was able to verify that `sendto` could send on the same socket that `sendmsg` was given. This seems to indicate that there's nothing wrong with the socket itself. Maybe `sendmsg` is failing for a different reason related to its other arguments. I will keep investigating.

**Comment by hildjj** [comment]
I wonder if the `from` address is wrong.  The whole reason for the split in v4/v6 was so that I could set the `from` address to match the `to` address in the packet that initiated the tube.  Also: see email for a Slack invite so we can discuss in realtime.

**Comment by hildjj** [comment]
I think we've got this for now.
